# -*- coding: utf-8 -*-
"""PLOTS_Muñoz_Escobar_Daniel_Arukin_S6CASA_EDO2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d4CAcgOfZvoHT_GYtLe7erTe5WKrtz0f
"""

import numpy as np
import matplotlib.pylab as plt
#Método de euler 2do orden
datos_euler_2orden=np.genfromtxt("metodo de euler EDO2orden",dtype=None, delimiter='|')

plt.figure()
plt.title('euler 2orden', fontsize=12)
plt.plot(datos_euler_2orden[:,0],datos_euler_2orden[:,1],'g')
plt.savefig("euler 2orden.pdf")

#Método de LeapFrog
datos_LeapFrog=np.genfromtxt("metodo de LeapFrog EDO2orden",dtype=None, delimiter='|')

plt.figure()
plt.title('LeapFrog', fontsize=12)
plt.plot(datos_LeapFrog[:,0],datos_LeapFrog[:,1],'y')
plt.savefig("LeapFrog")