# -*- coding: utf-8 -*-
"""PLOTS_Muñoz_Escobar_Daniel_Arukin_S6C2_EDO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2eAmeo6r0pn-c2Llwmd5ihZfSXExux8
"""

import numpy as np
import matplotlib.pylab as plt
#Método de euler
datos_euler=np.genfromtxt("metodo de euler",dtype=None, delimiter='|')

plt.figure()
plt.title('euler', fontsize=12)
plt.plot(datos_euler[:,0],datos_euler[:,1])
plt.savefig("euler.pdf")

#Método de Runge-Kutta de 4to
datos_Ruge_Kutta_4to=np.genfromtxt("metodo de Runge-Kutta de 4to",dtype=None, delimiter='|')

plt.figure()
plt.title('Ruge-Kutta de 4to', fontsize=12)
plt.plot(datos_Ruge_Kutta_4to[:,0],datos_Ruge_Kutta_4to[:,1],'r')
plt.savefig("Ruge-Kutta de 4to.pdf")